version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - url-shortener

  webserver:
    image: nginx:alpine
    container_name: url-shortener-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - url-shortener

networks:
  url-shortener:
    driver: bridge
